export const NAV_BY_ROLE = {
  SUPER_ADMIN: [
    { label: 'Dashboard', path: '/dashboard', icon: 'layout-dashboard' },
    { label: 'Employees', path: '/employees', icon: 'users' },
    { label: 'Payroll', path: '/payroll', icon: 'wallet' },
    { label: 'Attendance', path: '/attendance', icon: 'calendar-check' },
    { label: 'Leave', path: '/leave', icon: 'calendar-clock' },
    { label: 'Salary Structure', path: '/salary-structure', icon: 'badge-check' },
    { label: 'Payslips', path: '/payslips', icon: 'receipt' },
    { label: 'Reports', path: '/reports', icon: 'file-bar-chart' },
    { label: 'Tax & Compliance', path: '/tax-compliance', icon: 'landmark' },
    { label: 'Users & Roles', path: '/users', icon: 'shield-check' },
    { label: 'Audit Logs', path: '/audit-logs', icon: 'scroll-text' },
    { label: 'Notifications', path: '/notifications', icon: 'bell' },
    { label: 'Settings', path: '/settings', icon: 'settings' },
  ],
  HR_ADMIN: [
    { label: 'Dashboard', path: '/dashboard', icon: 'layout-dashboard' },
    { label: 'Employees', path: '/employees', icon: 'users' },
    { label: 'Attendance', path: '/attendance', icon: 'calendar-check' },
    { label: 'Leave', path: '/leave', icon: 'calendar-clock' },
    { label: 'Employee Documents', path: '/documents', icon: 'folder-open' },
    { label: 'Reports', path: '/reports', icon: 'file-bar-chart' },
    { label: 'Notifications', path: '/notifications', icon: 'bell' },
    { label: 'Settings', path: '/settings', icon: 'settings' },
  ],
  PAYROLL_ADMIN: [
    { label: 'Dashboard', path: '/dashboard', icon: 'layout-dashboard' },
    { label: 'Employees', path: '/employees', icon: 'users' },
    { label: 'Payroll', path: '/payroll', icon: 'wallet' },
    { label: 'Salary Structure', path: '/salary-structure', icon: 'badge-check' },
    { label: 'Payslips', path: '/payslips', icon: 'receipt' },
    { label: 'Tax & Compliance', path: '/tax-compliance', icon: 'landmark' },
    { label: 'Payroll Reports', path: '/reports', icon: 'file-bar-chart' },
    { label: 'Notifications', path: '/notifications', icon: 'bell' },
  ],
  MANAGER: [
    { label: 'Dashboard', path: '/dashboard', icon: 'layout-dashboard' },
    { label: 'My Team', path: '/my-team', icon: 'users-round' },
    { label: 'Attendance', path: '/attendance', icon: 'calendar-check' },
    { label: 'Leave Requests', path: '/leave', icon: 'calendar-clock' },
    { label: 'Team Reports', path: '/reports', icon: 'file-bar-chart' },
    { label: 'Notifications', path: '/notifications', icon: 'bell' },
    { label: 'Profile', path: '/profile', icon: 'user-circle' },
  ],
  EMPLOYEE: [
    { label: 'Dashboard', path: '/dashboard', icon: 'layout-dashboard' },
    { label: 'My Profile', path: '/profile', icon: 'user-circle' },
    { label: 'My Attendance', path: '/attendance', icon: 'calendar-check' },
    { label: 'My Leave', path: '/leave', icon: 'calendar-clock' },
    { label: 'My Payslips', path: '/payslips', icon: 'receipt' },
    { label: 'My Payroll', path: '/payroll', icon: 'wallet' },
    { label: 'Documents', path: '/documents', icon: 'folder-open' },
    { label: 'Notifications', path: '/notifications', icon: 'bell' },
    { label: 'Settings', path: '/settings', icon: 'settings' },
  ],
};
