# These values are stored as plain strings in the database (see
# db/migrations/001_init.sql) and enforced here at the Python/Pydantic boundary.

ROLE_NAMES = ["SUPER_ADMIN", "HR_ADMIN", "PAYROLL_ADMIN", "MANAGER", "EMPLOYEE"]
USER_STATUSES = ["ACTIVE", "INACTIVE", "LOCKED"]

RESOURCES = [
    "DASHBOARD",
    "EMPLOYEES",
    "PAYROLL",
    "ATTENDANCE",
    "LEAVE",
    "SALARY_STRUCTURE",
    "PAYSLIPS",
    "REPORTS",
    "USERS",
    "SETTINGS",
    "AUDIT_LOGS",
    "TAX_COMPLIANCE",
    "DEPARTMENTS",
    "DESIGNATIONS",
    "DOCUMENTS",
    "ANNOUNCEMENTS",
]

PERM_ACTIONS = ["VIEW", "CREATE", "EDIT", "DELETE", "APPROVE", "EXPORT", "PROCESS", "MANAGE"]

LEAVE_TYPES = ["ANNUAL", "SICK", "CASUAL", "UNPAID", "MATERNITY", "PATERNITY", "OTHER"]
LEAVE_STATUSES = ["PENDING", "APPROVED", "REJECTED", "CANCELLED"]
ATTENDANCE_STATUSES = ["PRESENT", "ABSENT", "HALF_DAY", "ON_LEAVE", "HOLIDAY", "WEEKEND"]
PAYROLL_STATUSES = [
    "DRAFT",
    "CALCULATING",
    "PENDING_REVIEW",
    "PENDING_APPROVAL",
    "APPROVED",
    "PROCESSING",
    "COMPLETED",
    "REJECTED",
    "FAILED",
]
EMPLOYEE_STATUSES = ["ONBOARDING", "ACTIVE", "OFFBOARDING", "OFFBOARDED"]
