// These values are stored as plain strings in the database (see
// db/migrations/001_init.sql) and enforced here at the JS/zod boundary.

const ROLE_NAMES = ['SUPER_ADMIN', 'HR_ADMIN', 'PAYROLL_ADMIN', 'MANAGER', 'EMPLOYEE'];
const USER_STATUSES = ['ACTIVE', 'INACTIVE', 'LOCKED'];

const RESOURCES = [
  'DASHBOARD',
  'EMPLOYEES',
  'PAYROLL',
  'ATTENDANCE',
  'LEAVE',
  'SALARY_STRUCTURE',
  'PAYSLIPS',
  'REPORTS',
  'USERS',
  'SETTINGS',
  'AUDIT_LOGS',
  'TAX_COMPLIANCE',
  'DEPARTMENTS',
  'DESIGNATIONS',
  'DOCUMENTS',
  'ANNOUNCEMENTS',
];

const PERM_ACTIONS = ['VIEW', 'CREATE', 'EDIT', 'DELETE', 'APPROVE', 'EXPORT', 'PROCESS', 'MANAGE'];

const LEAVE_TYPES = ['ANNUAL', 'SICK', 'CASUAL', 'UNPAID', 'MATERNITY', 'PATERNITY', 'OTHER'];
const LEAVE_STATUSES = ['PENDING', 'APPROVED', 'REJECTED', 'CANCELLED'];
const ATTENDANCE_STATUSES = ['PRESENT', 'ABSENT', 'HALF_DAY', 'ON_LEAVE', 'HOLIDAY', 'WEEKEND'];
const PAYROLL_STATUSES = ['DRAFT', 'CALCULATING', 'PENDING_REVIEW', 'PENDING_APPROVAL', 'APPROVED', 'PROCESSING', 'COMPLETED', 'REJECTED', 'FAILED'];
const EMPLOYEE_STATUSES = ['ONBOARDING', 'ACTIVE', 'OFFBOARDING', 'OFFBOARDED'];

module.exports = {
  ROLE_NAMES,
  USER_STATUSES,
  RESOURCES,
  PERM_ACTIONS,
  LEAVE_TYPES,
  LEAVE_STATUSES,
  ATTENDANCE_STATUSES,
  PAYROLL_STATUSES,
  EMPLOYEE_STATUSES,
};
